# Generated by Django 3.1.7 on 2021-03-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='slug',
            field=models.SlugField(default='teste1', editable=False, max_length=170),
            preserve_default=False,
        ),
    ]
