# Generated by Django 3.1.7 on 2021-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_build_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=170, null=True),
        ),
    ]
